const initialProducts = [
  {
    id: "littledutch-livre-forest",
    title: "Little Dutch Livre d'activités 'Forest Friends'",
    brand: "Little Dutch",
    category: "eveil",
    categoryLabel: "Éveil & Jouets",
    categoryIcon: "heart",
    price: 17.95,
    oldPrice: null,
    unitPrice: "17,95 €",
    rating: 4.9,
    reviewsCount: 142,
    store: "Dreambaby.be",
    storeUrl: "https://www.dreambaby.be/fr/products/little-dutch-livre-dactivites-forest-friends?_pos=7&_sid=6101aad73&_ss=r?variant=50889969271122",
    image: "images/littledutch-forest-friends.png",
    description: "Livre d'activités sensoriel et moelleux sur le thème enchanteur des amis de la forêt. Rempli de textures tactiles stimulantes, sons de froissement, anneau de dentition et miroir d'éveil.",
    isFavorite: false,
    allowPartial: false
  },
  {
    id: "ecohub-sac-voyage",
    title: "ECOHUB Sac de Voyage Femme 30L / Sac d'Hôpital & Maternité (Beige)",
    brand: "ECOHUB",
    category: "sorties",
    categoryLabel: "Sorties & Maternité",
    categoryIcon: "briefcase",
    price: 24.99,
    oldPrice: null,
    unitPrice: "24,99 €",
    rating: 4.5,
    reviewsCount: 1616,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/dp/B0CR5TS59D/?coliid=I1LC3DNF3T3K4E&colid=1JQM0H93GL2H&psc=1&ref_=list_c_wl_lv_vv_lig_dp_it",
    image: "images/ecohub-sac.png",
    description: "Sac week-end et valise de maternité multifonction 30L (45x36x20 cm) avec compartiment étanche amovible pour affaires humides. Élégant, ultra-pratique et résistant.",
    isFavorite: true,
    allowPartial: false
  },
  {
    id: "livre-contraste-noir-blanc",
    title: "Noir et Blanc : Livre Contraste Bébé – Stimulation Visuelle & Éveil (0 à 12 Mois)",
    brand: "Livre d'éveil",
    category: "eveil",
    categoryLabel: "Éveil & Jouets",
    categoryIcon: "heart",
    price: 5.26,
    oldPrice: null,
    unitPrice: "5,26 € (+ 2,50 € livraison)",
    rating: 4.8,
    reviewsCount: 340,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/Noir-Blanc-Livre-Contraste-B%C3%A9b%C3%A9/dp/B0BLG1F4MN/ref=mp_s_a_1_3?crid=32R69Y1PDZPAB&dib=eyJ2IjoiMSJ9.HWNzRjE_TzyWirgP6iC78MVr-mY2d6XGsP1fnJYal9GsTlIEYqqU53T1pYcW7mxSNLTrC87LO2dZdmiUPhfC3wdtpRfY9MMx9fmNLMTZlj1h7jH2LeAAuILUUqD2YeeNNAE_djY2xKcu61tBYgoxoReoCzXsL7prKrKY7qG-jGR0EELX16s1b0fr-Ieui5UWmp86NkGhpS2Wf9sicxV9vA.jMJfxyv_GT7_KL8sZmnhVUmF9tex_lTopNwyObXmgww&dib_tag=se&keywords=livre+contraste+bebe&qid=1790348005&sprefix=livre+contraste+bebe%2Caps%2C108&sr=8-3",
    image: "images/livre-contraste-noir-blanc.png",
    description: "Images et objets en noir et blanc à contraste élevé spécialement conçus pour stimuler le développement visuel et sensoriel des nouveau-nés dès les premiers jours.",
    isFavorite: false,
    allowPartial: false
  },
  {
    id: "vicloon-livre-sensoriel",
    title: "Vicloon Livre Sensoriel Souple & Miroir d'Éveil Double Face (Océan & Fruits)",
    brand: "Vicloon",
    category: "eveil",
    categoryLabel: "Éveil & Jouets",
    categoryIcon: "heart",
    price: 8.49,
    oldPrice: null,
    unitPrice: "8,49 €",
    rating: 4.4,
    reviewsCount: 5740,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/Vicloon-Montessori-Sensoriel-Favorise-D%C3%A9veloppement/dp/B0FH2RJDGD/ref=mp_s_a_1_8?crid=32R69Y1PDZPAB&dib=eyJ2IjoiMSJ9.HWNzRjE_TzyWirgP6iC78MVr-mY2d6XGsP1fnJYal9GsTlIEYqqU53T1pYcW7mxSNLTrC87LO2dZdmiUPhfC3wdtpRfY9MMx9fmNLMTZlj1h7jH2LeAAuILUUqD2YeeNNAE_djY2xKcu61tBYgoxoReoCzXsL7prKrKY7qG-jGR0EELX16s1b0fr-Ieui5UWmp86NkGhpS2Wf9sicxV9vA.jMJfxyv_GT7_KL8sZmnhVUmF9tex_lTopNwyObXmgww&dib_tag=se&keywords=livre%2Bcontraste%2Bbebe&qid=1790348005&sprefix=livre%2Bcontraste%2Bbebe%2Caps%2C108&sr=8-8&th=1",
    image: "images/vicloon-livre-sensoriel.png",
    description: "Livre accordéon d'inspiration Montessori double face avec 12 motifs contrastés et miroir d'éveil incassable. Pliable, réutilisable et lavable.",
    isFavorite: false,
    allowPartial: false
  },
  {
    id: "lionelo-pari-cododo",
    title: "Lionelo Pari Lit Cododo Bébé 3 en 1 avec Fonction Berceuse & Balancement (Beige)",
    brand: "Lionelo",
    category: "chambre",
    categoryLabel: "Chambre & Sommeil",
    categoryIcon: "home",
    price: 84.99,
    oldPrice: null,
    unitPrice: "84,99 €",
    rating: 4.6,
    reviewsCount: 138,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/Lionelo-Cododo-Berceau-Fonction-Berceuse/dp/B0GQ53PZSR/ref=sr_1_5?crid=3E8Y1D9APX1OG&dib=eyJ2IjoiMSJ9.W0y7BI51FBMyopiZP5s_eVg459SukTEVhwoIs-4wLkQ8ZNOkMqXSFf5LvAdir3m9fYX52DsDhY_qrStPQ0qOrQcPI3MOfIjR1QA3sKab-VyqWCwnydozqhhhit21LlsvvajQvriLjUXqCQ1eX_vGcmxgr4kWNTHycQ6Qg-L0ybemicnkfJ638iL445gHWRc2ps6Gpn4NggWDlyed4bkIc0QvIiGvv47mzKXz9ZgukTmjcbPNAtgymS2uE2TH-KeALpEH0z5miF31rFKGNgPbYSMkxarGtfqLNYVbDLjYit8.GaEKlUolm2ZmptT6iHcYNkaunfaALmtG2wTVIydN8nY&dib_tag=se&keywords=cododo%2Bbeige&qid=1790349063&sprefix=cododo%2Bbeig%2Caps%2C120&sr=8-5&th=1",
    image: "images/lionelo-pari-cododo.png",
    description: "Berceau cododo réglable en hauteur sur 6 niveaux, inclinable pour soulager le reflux, avec parois en maille respirante, fonction berceuse et roulettes avec frein.",
    isFavorite: true,
    allowPartial: false
  },
  {
    id: "nuby-anneau-dentition",
    title: "Nuby Teethe-eez Anneau de Dentition Souple en Silicone avec Étui (+3 Mois)",
    brand: "Nuby",
    category: "soins",
    categoryLabel: "Éveil & Soins",
    categoryIcon: "smile",
    price: 6.99,
    oldPrice: null,
    unitPrice: "6,99 € (étui inclus)",
    rating: 4.7,
    reviewsCount: 18250,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/Nuby-Teethe-eez-dentition-hygi%C3%A9nique-Turquoise/dp/B00IN8OJU8/ref=mp_s_a_1_11?crid=1QFTI7A6U3GID&dib=eyJ2IjoiMSJ9.Ut-dvLIsD5yDCbQBB7iJAv9ZcLUEWSLAUA2xgYwnBR12GjWDbZgYdUPaKYBdJx8dJd8KzDnwNTZeNBl9h4J4yojvq6xbzk2dqABAdtMJs893lg3lJ8rSIb9k_4QKpkIB-V5WF7e3gzQ7QNV0Xy-LvC_ArxfauOZaSMbtQwbhrB6C2nicPZUUy7hm1CCmKafS0g1jfRN7QWCKHRUjomj03w.MNFqhSVhNFLwsnD7cWjiStlKP9NICnth6J9WKn6NYpw&dib_tag=se&keywords=anneau%2Bde%2Bdentition%2Bbebe&qid=1790347351&sprefix=anneau%2Bde%2Bdentition%2Bbebe%2Caps%2C237&sr=8-11&th=1",
    image: "images/nuby-anneau-dentition.png",
    description: "Anneau de dentition 100% silicone souple avec surface massante pour soulager les gencives lors des poussées dentaires. Fourni avec son étui hygiénique de protection.",
    isFavorite: false,
    allowPartial: false
  },
  {
    id: "angelcare-transat-bain",
    title: "Angelcare - Transat de Bain Ergonomique et Sécurisant (0 à 6 Mois - Bleu)",
    brand: "Angelcare",
    category: "bain",
    categoryLabel: "Bain & Toilette",
    categoryIcon: "droplet",
    price: 28.50,
    oldPrice: null,
    unitPrice: "28,50 €",
    rating: 4.8,
    reviewsCount: 10796,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/dp/B00AWMV9CY/?coliid=I3H7NUNGB8MG0N&colid=1JQM0H93GL2H&psc=1&ref_=list_c_wl_lv_vv_lig_dp_it",
    image: "images/angelcare-transat.png",
    description: "Support de bain tout doux en matière perforée hygiénique et anti-moisissures. Épouse la morphologie de bébé pour des bains sereins et sécurisés en toute liberté.",
    isFavorite: false,
    allowPartial: false
  },
  {
    id: "mam-sucette-naissance",
    title: "MAM Sucette Perfect Naissance 0-2 mois (Lot de 2 tétines)",
    brand: "MAM",
    category: "repas",
    categoryLabel: "Repas & Sucettes",
    categoryIcon: "smile",
    price: 8.97,
    oldPrice: null,
    unitPrice: "4,48 € / pièce",
    rating: 4.8,
    reviewsCount: 60,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/dp/B0CNY3VNQ1/?coliid=I2LLUGLOYLT5Z7&colid=1JQM0H93GL2H&psc=1&ref_=list_c_wl_lv_vv_lig_dp_it",
    image: "images/mam-sucette-naissance.png",
    description: "Spécialement adaptées aux tout-petits nouveau-nés de 0 à 2 mois. Bouclier extra-léger et tétine mince pour respecter la mâchoire et les gencives délicates.",
    isFavorite: false,
    allowPartial: false
  },
  {
    id: "lionelo-poubelle-couches",
    title: "LIONELO Purebin Poubelle à Couches Anti-Odeur 10L avec Sacs Universels",
    brand: "Lionelo",
    category: "chambre",
    categoryLabel: "Chambre & Sommeil",
    categoryIcon: "home",
    price: 38.05,
    oldPrice: null,
    unitPrice: "38,05 €",
    rating: 4.2,
    reviewsCount: 108,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/dp/B0G49829M2/?coliid=I2ODNN2XDYQJZE&colid=1JQM0H93GL2H&psc=1&ref_=list_c_wl_lv_vv_lig_dp_it",
    image: "images/lionelo-poubelle.png",
    description: "Système de fermeture hermétique breveté bloquant 100% des mauvaises odeurs. Fonctionne avec des sacs poubelle standards (sans recharges coûteuses) et s'ouvre facilement d'une seule main.",
    isFavorite: true,
    allowPartial: false
  },
  {
    id: "molylove-brosse-bois",
    title: "Molylove Brosse Bébé en Bois Naturel & Poils de Chèvre Extra-Doux",
    brand: "Molylove",
    category: "soins",
    categoryLabel: "Soins & Hygiène",
    categoryIcon: "sparkles",
    price: 8.99,
    oldPrice: null,
    unitPrice: "8,99 €",
    rating: 4.6,
    reviewsCount: 13983,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/dp/B07XPS253G/?coliid=I1L65FVYF6MXQ5&colid=1JQM0H93GL2H&psc=1&ref_=list_c_wl_lv_vv_lig_dp_it",
    image: "images/molylove-brosse.png",
    description: "Manche en bois noble et soies naturelles de chèvre d'une douceur absolue. Idéal pour coiffer bébé avec délicatesse et prévenir les croûtes de lait sans irriter le cuir chevelu.",
    isFavorite: false,
    allowPartial: false
  },
  {
    id: "badabulle-balancelle",
    title: "Badabulle Balancelle Électrique Bébé 'Buddy Cream' (3 Vitesses & 8 Berceuses)",
    brand: "Badabulle",
    category: "eveil",
    categoryLabel: "Éveil & Confort",
    categoryIcon: "heart",
    price: 69.99,
    oldPrice: null,
    unitPrice: "69,99 €",
    rating: 4.2,
    reviewsCount: 96,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/Badabulle-Balancelle-Electrique-Balancement-Ber%C3%A7euses/dp/B0CKF6QPD8/ref=mp_s_a_1_29?adgrpid=152291738865&dib=eyJ2IjoiMSJ9.H5Th79fSKFqlx9pOU9X6Uldm15ycCbVtAAwqq7_CJOAxQz2Zpo6JiVjRfYDJ91gCE0aZW4w1V81rIj25pu_XYaoBCsiNx7LHW03mXzKTNrLaJw9TI8jFXHePciHb8xLDEo4Rm0q0vIttkZhY4uqHcFuYhLs_ttDb0XdU23uxNPIciqfWAgFT-TBMOLF2fR_nnH2U1tCZSX85S_JG7rPMVA.XATQJOYuraDrHVb819fXI2oBh34z6bnaYhGusCgH4lM&dib_tag=se&hvadid=820503864201&hvdev=m&hvexpln=0&hvlocphy=9197093&hvnetw=g&hvocijid=12918382347513881671--&hvqmt=e&hvrand=12918382347513881671&hvtargid=kwd-302113294292&hydadcr=28769_2610453&keywords=transat+b%C3%A9b%C3%A9+electrique&mcid=53cf70d91a1f3068bcd7514cabc3cf33&qid=1790348967&sr=8-29&xpid=0CHHGv4DXSeOm#averageCustomerReviewsAnchor",
    image: "images/badabulle-balancelle.png",
    description: "Balancelle automatique avec balancement latéral naturel, 3 vitesses réglables, minuterie, 8 douces berceuses et arche de jeux d'éveil suspendus.",
    isFavorite: true,
    allowPartial: false
  },
  {
    id: "littledutch-tapis-safari",
    title: "Little Dutch Tapis de Jeu & Éveil avec Arceau 'Safari Friends' Vert",
    brand: "Little Dutch",
    category: "eveil",
    categoryLabel: "Éveil & Jouets",
    categoryIcon: "heart",
    price: 74.95,
    oldPrice: null,
    unitPrice: "74,95 €",
    rating: 4.9,
    reviewsCount: 184,
    store: "Dreambaby.be",
    storeUrl: "https://www.dreambaby.be/fr/products/little-dutch-tapis-de-jeu-avec-arceau-safari-friends-vert?_pos=5&_sid=7e4fb4d88&_ss=r?variant=53636583653714",
    image: "images/littledutch-tapis.png",
    description: "Tapis d'éveil grand format ultra-rembourré avec arche amovible et 5 adorables jouets suspendus (animaux safari, grelot, hochet, miroir) pour des heures de découverte.",
    isFavorite: true,
    allowPartial: false
  },
  {
    id: "mam-sucette-nuit",
    title: "MAM | Sucette Perfect Nuit 2-6 mois (Lot de 2 pièces)",
    brand: "MAM",
    category: "repas",
    categoryLabel: "Repas & Sucettes",
    categoryIcon: "smile",
    price: 12.50,
    oldPrice: 13.90,
    unitPrice: "6,25 € / pièce",
    rating: 4.6,
    reviewsCount: 42,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/dp/B0CNY4GWG1/?coliid=I1AS9GJFOQBZME&colid=1JQM0H93GL2H&psc=1&ref_=list_c_wl_lv_vv_lig_dp_it",
    image: "images/mam-sucette-nuit.png",
    description: "Tétines en silicone ultra-doux phosphorescentes qui brillent dans le noir pour les retrouver facilement la nuit. Conçues pour un développement bucco-dentaire optimal.",
    isFavorite: false,
    allowPartial: false
  },
  {
    id: "arenti-babyphone-video",
    title: "ARENTI AINanny A4 Kit Plus Babyphone Vidéo 4MP avec Écran LCD 5\"",
    brand: "ARENTI",
    category: "chambre",
    categoryLabel: "Chambre & Sommeil",
    categoryIcon: "home",
    price: 139.89,
    oldPrice: null,
    unitPrice: "139,89 €",
    rating: 4.7,
    reviewsCount: 890,
    store: "Amazon.fr",
    storeUrl: "https://www.amazon.fr/ARENTI-AINanny-Kit-Plus-Inclinaison/dp/B0GN996HDB",
    image: "images/arenti-babyphone.png",
    description: "Écoute-bébé vidéo haute définition 4MP avec grand écran 5 pouces, caméra motorisée rotative à 360°, vision nocturne, suivi automatique des mouvements, berceuses et alertes.",
    isFavorite: true,
    allowPartial: false
  },
  {
    id: "support-babyphone-clip",
    title: "Support Universel à Clip pour Caméra Bébé & Babyphone (Baaletc)",
    brand: "Baaletc",
    category: "chambre",
    categoryLabel: "Chambre & Sommeil",
    categoryIcon: "home",
    price: 15.99,
    oldPrice: null,
    unitPrice: "15,99 €",
    rating: 4.6,
    reviewsCount: 214,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/Support-universel-babyphone-compatible-Hellobaby/dp/B0F8QSL3H1/ref=mp_s_a_1_2?crid=12BPRXP9K72GB&dib=eyJ2IjoiMSJ9.CQhhg18Ol-ya1dBpqN87L5jwy7j8mONpfj3J0hUT98clBU3k3ghPr5aA-k__Fh7hFrCe6jH-_z58nxN-ILkM3xS5VkxOMaNWQwVrpP5xHTjXKM9wJsHpL9cuuVPqo9u_xtumb9IKKRs4DOdyqQTYBH54VQjYNYvU2emHPHooZHnhQVdhQOd4JdyhKwnOz-P3vGCqCaHHAJjFu2gxeMVGVA.PJoaEqrUl6ShBvRezB6HqFZkrLwFSSaWApGUCCV89DU&dib_tag=se&keywords=support%2Buniversel%2Bbabyphone&qid=1786204352&sprefix=support%2Buni%2Caps%2C126&sr=8-2&th=1",
    image: "images/support-babyphone-clip.png",
    description: "Support flexible et robuste avec fixation à clip solide pour fixer facilement la caméra du babyphone au berceau, lit à barreaux ou étagère sans perçage.",
    isFavorite: false,
    allowPartial: false
  },
  {
    id: "babynova-aspirateur",
    title: "babynova Aspirateur Nasal avec Deux Embouts pour Bébés et Tout-Petits",
    brand: "BABY-NOVA",
    category: "soins",
    categoryLabel: "Soins & Hygiène",
    categoryIcon: "sparkles",
    price: 7.90,
    oldPrice: null,
    unitPrice: "7,90 € / unité",
    rating: 3.6,
    reviewsCount: 70,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/dp/B0GTM7DT76/?coliid=I11WOJW8VGA696&colid=1JQM0H93GL2H&psc=1&ref_=list_c_wl_lv_vv_lig_dp_it",
    image: "images/babynova-aspirateur.png",
    description: "Aspirateur nasal manuel avec deux embouts doux en silicone sans BPA. Permet un retrait doux et efficace du mucus nasal pour aider bébé à mieux respirer.",
    isFavorite: false,
    allowPartial: false
  },
  {
    id: "braun-mouche-bebe",
    title: "Braun Mouche-bébé 1 Électrique BNA100 (2 vitesses & 2 embouts)",
    brand: "Braun",
    category: "soins",
    categoryLabel: "Soins & Hygiène",
    categoryIcon: "sparkles",
    price: 28.27,
    oldPrice: null,
    unitPrice: "28,27 €",
    rating: 3.7,
    reviewsCount: 10537,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/dp/B07LD5NYWF/?coliid=I3JT2C78MVJ5AC&colid=1JQM0H93GL2H&psc=1&ref_=list_c_wl_lv_vv_lig_dp_it",
    image: "images/braun-mouche-bebe.png",
    description: "Débouche le nez rapidement et en douceur grâce à une aspiration électrique continue et silencieuse. Livré avec 2 tailles d'embouts souples lavables au lave-vaisselle.",
    isFavorite: false,
    allowPartial: false
  }
];
