const initialProducts = [
  {
    id: "littledutch-livre-forest",
    title: "Little Dutch Livre d'activités 'Forest Friends'",
    brand: "Little Dutch",
    category: "eveil",
    categoryLabel: "Éveil & Jouets",
    categoryIcon: "heart",
    price: 17.95,
    oldPrice: null,
    unitPrice: "17,95 €",
    rating: 4.9,
    reviewsCount: 142,
    store: "Dreambaby.be",
    storeUrl: "https://www.dreambaby.be/fr/products/little-dutch-livre-dactivites-forest-friends?_pos=7&_sid=6101aad73&_ss=r?variant=50889969271122",
    image: "images/littledutch-forest-friends.png",
    description: "Livre d'activités sensoriel et moelleux sur le thème enchanteur des amis de la forêt. Rempli de textures tactiles stimulantes, sons de froissement, anneau de dentition et miroir d'éveil.",
    isFavorite: true,
    allowPartial: false
  },
  {
    id: "ecohub-sac-voyage",
    title: "ECOHUB Sac de Voyage Femme 30L / Sac d'Hôpital & Maternité (Beige)",
    brand: "ECOHUB",
    category: "sorties",
    categoryLabel: "Sorties & Maternité",
    categoryIcon: "briefcase",
    price: 24.99,
    oldPrice: null,
    unitPrice: "24,99 €",
    rating: 4.5,
    reviewsCount: 1616,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/dp/B0CR5TS59D/?coliid=I1LC3DNF3T3K4E&colid=1JQM0H93GL2H&psc=1&ref_=list_c_wl_lv_vv_lig_dp_it",
    image: "images/ecohub-sac.png",
    description: "Sac week-end et valise de maternité multifonction 30L (45x36x20 cm) avec compartiment étanche amovible pour affaires humides. Élégant, ultra-pratique et résistant.",
    isFavorite: true,
    allowPartial: false
  },
  {
    id: "angelcare-transat-bain",
    title: "Angelcare - Transat de Bain Ergonomique et Sécurisant (0 à 6 Mois - Bleu)",
    brand: "Angelcare",
    category: "bain",
    categoryLabel: "Bain & Toilette",
    categoryIcon: "droplet",
    price: 28.50,
    oldPrice: null,
    unitPrice: "28,50 €",
    rating: 4.8,
    reviewsCount: 10796,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/dp/B00AWMV9CY/?coliid=I3H7NUNGB8MG0N&colid=1JQM0H93GL2H&psc=1&ref_=list_c_wl_lv_vv_lig_dp_it",
    image: "images/angelcare-transat.png",
    description: "Support de bain tout doux en matière perforée hygiénique et anti-moisissures. Épouse la morphologie de bébé pour des bains sereins et sécurisés en toute liberté.",
    isFavorite: false,
    allowPartial: false
  },
  {
    id: "alskvard-berceau",
    title: "IKEA ÄLSKVÄRD Berceau avec Matelas Respirant (Bouleau, 40x73 cm)",
    brand: "IKEA",
    category: "chambre",
    categoryLabel: "Chambre & Sommeil",
    categoryIcon: "home",
    price: 139.00,
    oldPrice: null,
    unitPrice: "139,00 €",
    rating: 4.9,
    reviewsCount: 245,
    store: "IKEA",
    storeUrl: "https://www.ikea.com/be/fr/p/aelskvaerd-berceau-avec-matelas-bouleau-s69556006/",
    image: "images/alskvard-berceau.png",
    description: "Élégant berceau en bouleau massif naturel avec matelas confortable inclus. Offre un cocon rassurant et un balancement doux pour les premières nuits de bébé.",
    isFavorite: true,
    allowPartial: false
  },
  {
    id: "mam-sucette-naissance",
    title: "MAM Sucette Perfect Naissance 0-2 mois (Lot de 2 tétines)",
    brand: "MAM",
    category: "repas",
    categoryLabel: "Repas & Sucettes",
    categoryIcon: "smile",
    price: 8.97,
    oldPrice: null,
    unitPrice: "4,48 € / pièce",
    rating: 4.8,
    reviewsCount: 60,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/dp/B0CNY3VNQ1/?coliid=I2LLUGLOYLT5Z7&colid=1JQM0H93GL2H&psc=1&ref_=list_c_wl_lv_vv_lig_dp_it",
    image: "images/mam-sucette-naissance.png",
    description: "Spécialement adaptées aux tout-petits nouveau-nés de 0 à 2 mois. Bouclier extra-léger et tétine mince pour respecter la mâchoire et les gencives délicates.",
    isFavorite: false,
    allowPartial: false
  },
  {
    id: "lionelo-poubelle-couches",
    title: "LIONELO Purebin Poubelle à Couches Anti-Odeur 10L avec Sacs Universels",
    brand: "Lionelo",
    category: "chambre",
    categoryLabel: "Chambre & Sommeil",
    categoryIcon: "home",
    price: 38.05,
    oldPrice: null,
    unitPrice: "38,05 €",
    rating: 4.2,
    reviewsCount: 108,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/dp/B0G49829M2/?coliid=I2ODNN2XDYQJZE&colid=1JQM0H93GL2H&psc=1&ref_=list_c_wl_lv_vv_lig_dp_it",
    image: "images/lionelo-poubelle.png",
    description: "Système de fermeture hermétique breveté bloquant 100% des mauvaises odeurs. Fonctionne avec des sacs poubelle standards (sans recharges coûteuses) et s'ouvre facilement d'une seule main.",
    isFavorite: true,
    allowPartial: false
  },
  {
    id: "molylove-brosse-bois",
    title: "Molylove Brosse Bébé en Bois Naturel & Poils de Chèvre Extra-Doux",
    brand: "Molylove",
    category: "soins",
    categoryLabel: "Soins & Hygiène",
    categoryIcon: "sparkles",
    price: 8.99,
    oldPrice: null,
    unitPrice: "8,99 €",
    rating: 4.6,
    reviewsCount: 13983,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/dp/B07XPS253G/?coliid=I1L65FVYF6MXQ5&colid=1JQM0H93GL2H&psc=1&ref_=list_c_wl_lv_vv_lig_dp_it",
    image: "images/molylove-brosse.png",
    description: "Manche en bois noble et soies naturelles de chèvre d'une douceur absolue. Idéal pour coiffer bébé avec délicatesse et prévenir les croûtes de lait sans irriter le cuir chevelu.",
    isFavorite: false,
    allowPartial: false
  },
  {
    id: "littledutch-tapis-safari",
    title: "Little Dutch Tapis de Jeu & Éveil avec Arceau 'Safari Friends' Vert",
    brand: "Little Dutch",
    category: "eveil",
    categoryLabel: "Éveil & Jouets",
    categoryIcon: "heart",
    price: 74.95,
    oldPrice: null,
    unitPrice: "74,95 €",
    rating: 4.9,
    reviewsCount: 184,
    store: "Dreambaby.be",
    storeUrl: "https://www.dreambaby.be/fr/products/little-dutch-tapis-de-jeu-avec-arceau-safari-friends-vert?_pos=5&_sid=7e4fb4d88&_ss=r?variant=53636583653714",
    image: "images/littledutch-tapis.png",
    description: "Tapis d'éveil grand format ultra-rembourré avec arche amovible et 5 adorables jouets suspendus (animaux safari, grelot, hochet, miroir) pour des heures de découverte.",
    isFavorite: true,
    allowPartial: false
  },
  {
    id: "mam-sucette-nuit",
    title: "MAM | Sucette Perfect Nuit 2-6 mois (Lot de 2 pièces)",
    brand: "MAM",
    category: "repas",
    categoryLabel: "Repas & Sucettes",
    categoryIcon: "smile",
    price: 12.50,
    oldPrice: 13.90,
    unitPrice: "6,25 € / pièce",
    rating: 4.6,
    reviewsCount: 42,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/dp/B0CNY4GWG1/?coliid=I1AS9GJFOQBZME&colid=1JQM0H93GL2H&psc=1&ref_=list_c_wl_lv_vv_lig_dp_it",
    image: "images/mam-sucette-nuit.png",
    description: "Tétines en silicone ultra-doux phosphorescentes qui brillent dans le noir pour les retrouver facilement la nuit. Conçues pour un développement bucco-dentaire optimal.",
    isFavorite: false,
    allowPartial: false
  },
  {
    id: "arenti-babyphone-video",
    title: "ARENTI AINanny A4 Kit Plus Babyphone Vidéo 4MP avec Écran LCD 5\"",
    brand: "ARENTI",
    category: "chambre",
    categoryLabel: "Chambre & Sommeil",
    categoryIcon: "home",
    price: 139.89,
    oldPrice: null,
    unitPrice: "139,89 €",
    rating: 4.7,
    reviewsCount: 890,
    store: "Amazon.fr",
    storeUrl: "https://www.amazon.fr/ARENTI-AINanny-Kit-Plus-Inclinaison/dp/B0GN996HDB",
    image: "images/arenti-babyphone.png",
    description: "Écoute-bébé vidéo haute définition 4MP avec grand écran 5 pouces, caméra motorisée rotative à 360°, vision nocturne, suivi automatique des mouvements, berceuses et alertes.",
    isFavorite: true,
    allowPartial: false
  },
  {
    id: "babynova-aspirateur",
    title: "babynova Aspirateur Nasal avec Deux Embouts pour Bébés et Tout-Petits",
    brand: "BABY-NOVA",
    category: "soins",
    categoryLabel: "Soins & Hygiène",
    categoryIcon: "sparkles",
    price: 7.90,
    oldPrice: null,
    unitPrice: "7,90 € / unité",
    rating: 3.6,
    reviewsCount: 70,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/dp/B0GTM7DT76/?coliid=I11WOJW8VGA696&colid=1JQM0H93GL2H&psc=1&ref_=list_c_wl_lv_vv_lig_dp_it",
    image: "images/babynova-aspirateur.png",
    description: "Aspirateur nasal manuel avec deux embouts doux en silicone sans BPA. Permet un retrait doux et efficace du mucus nasal pour aider bébé à mieux respirer.",
    isFavorite: false,
    allowPartial: false
  },
  {
    id: "braun-mouche-bebe",
    title: "Braun Mouche-bébé 1 Électrique BNA100 (2 vitesses & 2 embouts)",
    brand: "Braun",
    category: "soins",
    categoryLabel: "Soins & Hygiène",
    categoryIcon: "sparkles",
    price: 28.27,
    oldPrice: null,
    unitPrice: "28,27 €",
    rating: 3.7,
    reviewsCount: 10537,
    store: "Amazon.com.be",
    storeUrl: "https://www.amazon.com.be/dp/B07LD5NYWF/?coliid=I3JT2C78MVJ5AC&colid=1JQM0H93GL2H&psc=1&ref_=list_c_wl_lv_vv_lig_dp_it",
    image: "images/braun-mouche-bebe.png",
    description: "Débouche le nez rapidement et en douceur grâce à une aspiration électrique continue et silencieuse. Livré avec 2 tailles d'embouts souples lavables au lave-vaisselle.",
    isFavorite: false,
    allowPartial: false
  }
];
